export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REDIRECT = 'REDIRECT';

export const APP_LOAD = 'APP_LOAD';
export const DASHBOARD_LOADED = 'DASHBOARD_LOADED';
export const FETCH_USER = 'FETCH_USER';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_POSTS = 'FETCH_POSTS';
export const SEND_DASHBOARD_MESSAGE = 'SEND_DASHBOARD_MESSAGE';
export const DELETE_DASHBOARD_MESSAGE = 'DELETE_MESSAGE';
export const EDIT_DASHBOARD_MESSAGE = 'EDIT_MESSAGE';

export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const EXPAND_MESSAGE = 'EXPAND_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const EDIT_PROFILE_DATA = 'EDIT_PROFILE_DATA';
export const SUBMIT_PROFILE_DATA = 'SUBMIT_PROFILE_DATA';