export const CURRENT_USER = [
  {
    profile: {
      userName: 'lydiahallie',
      img: 'https://pbs.twimg.com/profile_images/933660989802807296/maudzPZE_400x400.jpg',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Lydia',
    lastName: 'Hallie',
    __v: 0,
  },
];

export const ALL_USERS = [
  {
    profile: {
      userName: 'lydiahallie',
      img: 'https://pbs.twimg.com/profile_images/933660989802807296/maudzPZE_400x400.jpg',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Lydia',
    lastName: 'Hallie',
    __v: 0,
  },
  {
    profile: {
      userName: 'johndoe',
      img: 'https://randomuser.me/api/portraits/men/33.jpg',
      title: 'Backend Developer',
      skills: [
        { lang: 'Java', value: 90 },
        { lang: 'Ruby', value: 80 },
        { lang: 'C', value: 60 },
      ],
      level: 'Advanced',
      description: 'I love everything about backend',
    },
    firstName: 'John',
    lastName: 'Doe',
    __v: 0,
  },
  {
    profile: {
      userName: 'sarahjohnson',
      img: 'https://randomuser.me/api/portraits/women/59.jpg',
      title: 'Front End Engineer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Python', value: 90 },
        { lang: 'Ruby on Rails', value: 70 },
      ],
      level: 'Advanced',
      description: 'I am an experience front end engineer who works a lot with JavaScript, Python and RoR.',
    },
    firstName: 'Sarah',
    lastName: 'Johnson',
    __v: 0,
  },
  {
    profile: {
      userName: 'stevegreen',
      img: 'https://randomuser.me/api/portraits/men/64.jpg',
      title: 'Web Designer',
      skills: [
        { lang: 'HTML', value: 95 },
        { lang: 'CSS', value: 95 },
        { lang: 'jQuery', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a web designer who loves to design websites.",
    },
    firstName: 'Steve',
    lastName: 'Green',
    __v: 0,
  },
  {
    profile: {
      userName: 'eulatliam',
      img: 'https://randomuser.me/api/portraits/women/61.jpg',
      title: 'Security Engineer',
      skills: [
        { lang: 'Python', value: 95 },
        { lang: 'C', value: 90 },
        { lang: 'C++', value: 80 },
      ],
      level: 'Advanced',
      description: 'I have a lot of experience in application security.',
    },
    firstName: 'Eulalia',
    lastName: 'Matheson',
    __v: 0,
  },
  {
    profile: {
      userName: 'sarawade',
      img: 'https://randomuser.me/api/portraits/women/10.jpg',
      title: 'UI/UX Engineer',
      skills: [
        { lang: 'CSS', value: 100 },
        { lang: 'HTML', value: 97 },
        { lang: 'Sass', value: 90 },
      ],
      level: 'Advanced',
      description: 'I am an art school graduate who has designed websites for tech giants.',
    },
    firstName: 'Sara',
    lastName: 'Wade',
    __v: 0,
  },
  {
    profile: {
      userName: 'sigurdr',
      img: 'https://randomuser.me/api/portraits/men/18.jpg',
      title: 'CompSci Student',
      skills: [
        { lang: 'Ruby', value: 80 },
        { lang: 'Java', value: 70 },
        { lang: 'Python', value: 60 },
      ],
      level: 'Advanced',
      description: "I'm a computer science student in Iceland, working on strengthening my backend skills.",
    },
    firstName: 'Sigurðr',
    lastName: ' Melvin',
    __v: 0,
  },
  {
    profile: {
      userName: 'hubertberan',
      img: 'https://randomuser.me/api/portraits/men/74.jpg',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'C++', value: 90 },
        { lang: 'F#', value: 90 },
        { lang: 'Haskell', value: 80 },
      ],
      level: 'Advanced',
      description: 'I am a computer programmer who has worked a lot with game developement.',
    },
    firstName: 'Hubert',
    lastName: 'Beran',
    __v: 0,
  },
  {
    profile: {
      userName: 'quanahmihov',
      img: 'https://randomuser.me/api/portraits/women/82.jpg',
      title: 'Web Developer',
      skills: [
        { lang: 'HTML', value: 75 },
        { lang: 'CSS', value: 74 },
        { lang: 'Python', value: 70 },
      ],
      level: 'Advanced',
      description: "I'm an amateur web developer",
    },
    firstName: 'Quanah',
    lastName: 'Mihov',
    __v: 0,
  },
  {
    profile: {
      userName: 'kristiina',
      img: 'https://randomuser.me/api/portraits/women/11.jpg',
      title: 'Android Developer',
      skills: [
        { lang: 'Swift', value: 95 },
        { lang: 'Java', value: 90 },
        { lang: 'Go', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Kristiina',
    lastName: 'Thomas',
    __v: 0,
  },
  {
    profile: {
      userName: 'adrienne',
      img: 'https://randomuser.me/api/portraits/women/58.jpg',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm an experienced web developer",
    },
    firstName: 'Adrienne',
    lastName: 'Hashimoto',
    __v: 0,
  },
  {
    profile: {
      userName: 'rosalinaholub',
      img: 'https://randomuser.me/api/portraits/women/28.jpg',
      title: 'Backend Engineer',
      skills: [
        { lang: 'Java', value: 95 },
        { lang: 'Ruby', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: 'I am a backend engineer who works on 2D games in my free time!',
    },
    firstName: 'Rosalina',
    lastName: 'Holub',
    __v: 0,
  },
  {
    profile: {
      userName: 'matirtza',
      img: 'https://randomuser.me/api/portraits/women/77.jpg',
      title: 'Software Engineer',
      skills: [
        { lang: 'C++', value: 80 },
        { lang: 'C#', value: 80 },
        { lang: 'C', value: 70 },
      ],
      level: 'Advanced',
      description: "I'm an amateur embedded software engineer.",
    },
    firstName: 'Maritza',
    lastName: 'Novosad',
    __v: 0,
  },
  {
    profile: {
      userName: 'marinahewitt',
      img: 'https://randomuser.me/api/portraits/women/68.jpg',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Marina',
    lastName: 'Hewitt',
    __v: 0,
  },
  {
    profile: {
      userName: 'meravkuiper',
      img: 'https://randomuser.me/api/portraits/men/28.jpg',
      title: 'Front End Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Swift', value: 90 },
        { lang: 'Ruby', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a front end developer who is always coding in his freetime!",
    },
    firstName: 'Merav',
    lastName: 'Kuiper',
    __v: 0,
  },
  {
    profile: {
      userName: 'lydiahallie',
      img: 'http://fuuse.net/wp-content/uploads/2016/02/avatar-placeholder.png',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Mosi',
    lastName: 'Holzer',
    __v: 0,
  },
  {
    profile: {
      userName: 'lydiahallie',
      img: 'https://randomuser.me/api/portraits/men/86.jpg',
      title: 'Software Developer',
      skills: [
        { lang: 'Python', value: 95 },
        { lang: 'Java', value: 90 },
        { lang: 'C', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a backend engineer and student.",
    },
    firstName: 'Iseul',
    lastName: 'Biskup',
    __v: 0,
  },
  {
    profile: {
      userName: 'lydiahallie',
      img: 'http://fuuse.net/wp-content/uploads/2016/02/avatar-placeholder.png',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Nikhil',
    lastName: 'Jedlička',
    __v: 0,
  },
  {
    profile: {
      userName: 'lydiahallie',
      img: 'http://fuuse.net/wp-content/uploads/2016/02/avatar-placeholder.png',
      title: 'JavaScript Developer',
      skills: [
        { lang: 'JavaScript', value: 95 },
        { lang: 'Sass', value: 90 },
        { lang: 'Python', value: 80 },
      ],
      level: 'Advanced',
      description: "I'm a highly motivated JavaScript developer who is always looking for interesting side projects!",
    },
    firstName: 'Jóna',
    lastName: 'Mutton',
    __v: 0,
  },
];
